name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  NPM_VERSION: '9.5.0'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint -- --max-warnings 10
        continue-on-error: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_URL: '/personal-portfolio/'

      - name: Copy config files to dist
        run: |
          cp public/.nojekyll dist/
          cp public/_headers dist/
          echo "{}" > dist/vercel.json
          echo "window.BUILD_MODE = 'production';" > dist/config.js
          
      - name: Create .nojekyll file
        run: touch dist/.nojekyll
        
      - name: Create headers file for GitHub Pages
        run: |
          cat > dist/_headers << EOL
          /*
            Content-Type: text/html; charset=utf-8
            X-Content-Type-Options: nosniff
            Permissions-Policy: interest-cohort=()
          
          /*.js
            Content-Type: application/javascript; charset=utf-8
          
          /*.css
            Content-Type: text/css; charset=utf-8
          EOL

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
